### ISSUE TITLE
The minimum required Python version for python-duckdb 1.0.0 may be incorrect

### ISSUE THREAD

**Issue by qingfei1994** [conda-forge/python-duckdb-feedstock#110]
### Comment:

Documents in duckdb for Python API shows that the minimum required Python version is 3.7.0
However, when I tried to install python-duckdb 1.0.0 in my Conda environment with Python 3.7.12, I encountered the following error:

```
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.7.* , which can be installed;
└─ python-duckdb 1.0.0**  is not installable because there are no viable options
   ├─ python-duckdb 1.0.0 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ python-duckdb 1.0.0 would require
   │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
   ├─ python-duckdb 1.0.0 would require
   │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
   ├─ python-duckdb 1.0.0 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   └─ python-duckdb 1.0.0 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.
```
I used below command to install python-duckdb in my Conda enviroment.
`conda install python-duckdb=1.0.0 -c conda-forge`

May I know if something went wrong or I'm not using it in a right way?

**Comment by gforsyth** [comment]
Hi @qingfei1994 -- packages built on conda-forge don't support Python versions that are at End Of Life -- security support for Python 3.7 ended in June of 2023, so there are no new packages being built on conda-forge for Python 3.7.

I would recommend that you upgrade the version of Python in your conda environment (and note that Python 3.8 is going to be EOL at the end of October 2024).

If you are constrained by your employer to use an outdated version of Python, you can try to install DuckDB using `pip`.
