### ISSUE TITLE
Windows release missing

### ISSUE THREAD

**Issue by juanfcocontreras** [conda-forge/python-duckdb-feedstock#39]
Is there a technical reason for the Windows version not being available? The package is great and in principle very portable.

Thank you very much in advance!

**Comment by rgoubet** [comment]
Definitely needed. It's actually available on PyPI.

**Comment by metab0t** [comment]
I think we can close this issue now?

**Comment by juanfcocontreras** [comment]
Yes, it is now available. Thanks @metab0t for your work
