### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by rgoubet** [conda-forge/python-duckdb-feedstock#98]
### Comment:

The package still won't install with Python 3.12. Was it not supposed to be supported with version 0.10.0?

**Comment by zaneselvans** [comment]
Is there any chance that #99 / v0.10.1 might be able to add Python 3.12 support to the conda package?  Is there something blocking it?

**Comment by xhochy** [comment]
See https://conda-forge.org/status/migration/python312, the bot currently fails to solve the recipe for 3.12.

**Comment by rgoubet** [comment]
Still not supported with 0.10.1. I hope this is fixed soon!

**Comment by xhochy** [comment]
@rgoubet See the above message on what we're waiting on.

**Comment by rgoubet** [comment]
It doesn't explain much, so I hope you figure this out soon. Thanks for your work on this!
